// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE4OPWIvw5-ATJTZ24BitFEOtWqTVM_fM',
    appId: '1:100425054539:web:8b258746eda73cc58ed0ce',
    messagingSenderId: '100425054539',
    projectId: 'chat-app-a444f',
    authDomain: 'chat-app-a444f.firebaseapp.com',
    storageBucket: 'chat-app-a444f.appspot.com',
    measurementId: 'G-PV1G6MQJ2L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUbVunt1_ooZZtIdMS46pEJ8Z5F6qNSPU',
    appId: '1:100425054539:android:0fc97bec7ba74c7d8ed0ce',
    messagingSenderId: '100425054539',
    projectId: 'chat-app-a444f',
    storageBucket: 'chat-app-a444f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqZdbheh0qBYXExWvVZm21-7QR9QAHfB8',
    appId: '1:100425054539:ios:76e6616c002012868ed0ce',
    messagingSenderId: '100425054539',
    projectId: 'chat-app-a444f',
    storageBucket: 'chat-app-a444f.appspot.com',
    iosClientId: '100425054539-h197c1loc5jp1mc0t9oicn3ncot1ln8v.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqZdbheh0qBYXExWvVZm21-7QR9QAHfB8',
    appId: '1:100425054539:ios:76e6616c002012868ed0ce',
    messagingSenderId: '100425054539',
    projectId: 'chat-app-a444f',
    storageBucket: 'chat-app-a444f.appspot.com',
    iosClientId: '100425054539-h197c1loc5jp1mc0t9oicn3ncot1ln8v.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
